deploy_production:
  environment: production
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html" --include "*.txt" --include ".pdf" --include "*.ps" --include "*.asc"
  only:
  - master

