apiVersion: v1
kind: Service
metadata:
  name: static-svc
  labels:
    app: static
    version: 1.0.0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: static-web
    version: 1.0.0
  loadBalancerIP: 130.211.48.66
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: static-web
        version: 1.0.0
    spec:
      containers:
      - name: static-web-server
        image: eu.gcr.io/worldofnic-production/static:latest
        ports:
        - containerPort: 80
        - containerPort: 443
