apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: static-web
        version: 1.0.0
    spec:
      containers:
      - name: static-web-server
        image: eu.gcr.io/worldofnic-production/static:1.2.1
        ports:
        - containerPort: 80
        - containerPort: 443
